### ISSUE TITLE
Slim down tests

### ISSUE THREAD

**Issue by stefanrueger** [MCUdude/avrdude-test-script#15]
Testing a programmer/part combo with large flash/eeprom can take long.  In the first instance -U memory:v:... can be removed as in absence of -V the preceding -U memory:w:... will already carry out a verify. Maybe we only write one file per memory with holes and only if that fails do another test writing the full memory from 0. Checking whether 0s can be flipped to 1s can be done with a simpler -U eeprom:w:0x55:m -U eeprom:w:0xaa:m (one byte is enough) and that test can be named "flip 0 to 1". There may be more tricks to make test cases orthogonal and reduce the time for the full test procedure.

**Comment by MCUdude** [comment]
Resolved in #20
