### ISSUE TITLE
To support bootloader test

### ISSUE THREAD

**Issue by mcuee** [MCUdude/avrdude-test-script#2]
* https://github.com/avrdudes/avrdude/discussions/1473#discussioncomment-8042321

One missing feature of the repo is how to test bootloaders -- some of the hex files can not be used in this case as part of the Flash (at the end or at the beginning) can not be used.

Bootloaders to be tested: mainly urclock, optiboot (stk500v1), stk500v2, optiboot_x and optiboot_dx, avr109 (eg: Arduino Leonardo which also needs 1200bps touch). The others may be Micronucleus, Flip1/Flip2 and Teensy.

Survey of AVR bootloaders:
* https://github.com/avrdudes/avrdude/discussions/1058

**Comment by MCUdude** [comment]
Fixed in [bfdcadd](https://github.com/MCUdude/avrdude-test-script/commit/bfdcadda8b6e34b4bd9c29771efe9aa8a2f16416)

**Comment by mcuee** [comment]
My original intention is to have two sets of files, the original set for programmers and the new set for bootloaders.

But I think your fix is also valid -- to use the same sets of files for the test.
