### ISSUE TITLE
To be able to show the time duration for the test to complete

### ISSUE THREAD

**Issue by mcuee** [MCUdude/avrdude-test-script#4]
It will be great to be able to show the time duration for each test to complete.

**Comment by MCUdude** [comment]
Not sure how that should be accomplished. But PRs are always welcome!

**Comment by mcuee** [comment]
Something like this.
https://www.hostinger.com/tutorials/linux-time-command/

But I think this is not so important. So I will close this.

**Comment by MCUdude** [comment]
@stefanrueger my bash-fu skills are not all that great, so this isn't all that trivial for me to implement. However, do you see an easy solution to this? Measuring the time it takes to run Avrdude is useful for benchmarking

**Comment by stefanrueger** [comment]
Well, there are a gazillion of timing techniques. If you want wall-clock execution times for each avrdude execution consider the following technique (the variable needs only setting once)
``` bash
TIMEFORMAT=%R
{ time sleep 0.2; } 2>&1
0.204
```
Note the semicolon in the curly brackets after the command to be timed.
